"""
Week 4 - Data cleaning on the Week 1 combined dataset.

Prerequisite (do this first, not in this script):
  1. Copy the new raw monthly files (e.g. CRMLSListing202605.csv,
     CRMLSListing202606.csv, CRMLSSold202605.csv, CRMLSSold202606.csv) into
     the same folder as the other monthly raw files.
  2. Add the new months to the MONTHS list in week1_aggregation.py:
       "202601", "202602", "202603", "202604", "202605", "202606",
  3. Rerun week1_aggregation.py. It reprocesses every month in MONTHS from
     scratch and overwrites CRMLSListing_Combined_Residential.csv /
     CRMLSSold_Combined_Residential.csv with the full, updated dataset.

This script then picks up those regenerated combined files and runs Week 4
cleaning on them:
  - remove redundant duplicate-named columns
  - datetime conversion
  - numeric type enforcement + invalid value flags
  - date consistency flags
  - geographic data quality flags

Note: raw Listing exports contain 11 duplicate column names (PropertyType,
CloseDate, Latitude, etc.), which pandas auto-renames to a '.1' suffix on
read (e.g. 'PropertyType.1'). Week 1 never dropped these, so they carry
through into the combined file - this script removes them as part of the
"remove redundant columns" task (see drop_redundant_columns() below).
"""

import pandas as pd
from pathlib import Path

# ---------------------------------------------------------------------------
# CONFIG - update this path to match your local directory structure
# ---------------------------------------------------------------------------
BASE_DIR = Path(r"C:\IDX-Exchange\csv")

# Regenerated by rerunning week1_aggregation.py with the updated MONTHS list
COMBINED_LISTING_PATH = BASE_DIR / "CRMLSListing_Combined_Residential.csv"
COMBINED_SOLD_PATH = BASE_DIR / "CRMLSSold_Combined_Residential.csv"

# Week 4 outputs
CLEANED_LISTING_PATH = BASE_DIR / "week4_cleaned_listing.csv"
CLEANED_SOLD_PATH = BASE_DIR / "week4_cleaned_sold.csv"

DATE_COLS = [
    "CloseDate",
    "PurchaseContractDate",
    "ListingContractDate",
    "ContractStatusChangeDate",
]
NUMERIC_COLS = [
    "ClosePrice",
    "LivingArea",
    "DaysOnMarket",
    "BedroomsTotal",
    "BathroomsTotalInteger",
]

# California bounding box for plausibility checks
CA_LAT_RANGE = (32.0, 42.0)
CA_LNG_RANGE = (-125.0, -114.0)


# ---------------------------------------------------------------------------
# Week 4 cleaning
# ---------------------------------------------------------------------------
def drop_redundant_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Drop the '.1'-suffixed duplicate columns created when pandas read the
    raw files (PropertyType.1, CloseDate.1, etc.). Verifies the dropped
    duplicate matches the kept original wherever both are non-null before
    dropping, so we don't silently lose diverging data."""
    dup_cols = [c for c in df.columns if c.endswith(".1")]
    for dup in dup_cols:
        original = dup[:-2]
        if original in df.columns:
            both_filled = df[original].notna() & df[dup].notna()
            mismatches = (df.loc[both_filled, original].astype(str)
                          != df.loc[both_filled, dup].astype(str)).sum()
            if mismatches:
                print(f"  WARNING: '{original}' vs '{dup}' differ in {mismatches:,} rows - kept '{original}', dropped '{dup}'")
    if dup_cols:
        print(f"  Dropped {len(dup_cols)} redundant duplicate-named columns: {dup_cols}")
        df = df.drop(columns=dup_cols)
    return df


def clean_dataset(df: pd.DataFrame, label: str) -> pd.DataFrame:
    print(f"\n--- Cleaning {label} ---")
    before_rows = len(df)

    # 0. Remove redundant columns
    df = drop_redundant_columns(df)

    # 1. Datetime conversion
    for col in DATE_COLS:
        if col in df.columns:
            failed_before = df[col].notna().sum()
            df[col] = pd.to_datetime(df[col], errors="coerce")
            failed_after = df[col].isna().sum() - (before_rows - failed_before)
            print(f"  {col}: converted to datetime "
                  f"({max(failed_after, 0):,} values could not be parsed)")

    # 2. Numeric type enforcement
    for col in NUMERIC_COLS:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # 3. Invalid numeric value flags
    df["invalid_price_flag"] = df.get("ClosePrice", pd.Series(dtype=float)) <= 0
    df["invalid_area_flag"] = df.get("LivingArea", pd.Series(dtype=float)) <= 0
    df["invalid_dom_flag"] = df.get("DaysOnMarket", pd.Series(dtype=float)) < 0
    df["invalid_beds_baths_flag"] = (
        (df.get("BedroomsTotal", pd.Series(dtype=float)) < 0)
        | (df.get("BathroomsTotalInteger", pd.Series(dtype=float)) < 0)
    )

    # 4. Date consistency flags
    df["listing_after_close_flag"] = df["ListingContractDate"] > df["CloseDate"]
    df["purchase_after_close_flag"] = df["PurchaseContractDate"] > df["CloseDate"]
    df["negative_timeline_flag"] = df["ListingContractDate"] > df["PurchaseContractDate"]

    # 5. Geographic checks
    df["missing_coord_flag"] = df["Latitude"].isna() | df["Longitude"].isna()
    df["zero_coord_flag"] = (df["Latitude"] == 0) | (df["Longitude"] == 0)
    df["positive_lng_flag"] = df["Longitude"] > 0
    df["out_of_ca_bounds_flag"] = ~df["Latitude"].between(*CA_LAT_RANGE) | ~df["Longitude"].between(*CA_LNG_RANGE)

    # Summary
    flag_cols = [c for c in df.columns if c.endswith("_flag")]
    print(f"  Rows: {before_rows:,} (row count unchanged - invalid records are flagged, not dropped)")
    for col in flag_cols:
        print(f"  {col}: {int(df[col].sum()):,} flagged")

    return df


def main():
    listing = pd.read_csv(COMBINED_LISTING_PATH, low_memory=False)
    sold = pd.read_csv(COMBINED_SOLD_PATH, low_memory=False)
    print(f"Loaded combined Listing: {len(listing):,} rows")
    print(f"Loaded combined Sold: {len(sold):,} rows")

    listing_clean = clean_dataset(listing, "Listing")
    sold_clean = clean_dataset(sold, "Sold")

    listing_clean.to_csv(CLEANED_LISTING_PATH, index=False)
    sold_clean.to_csv(CLEANED_SOLD_PATH, index=False)

    print(f"\nSaved cleaned Listing dataset -> {CLEANED_LISTING_PATH}")
    print(f"Saved cleaned Sold dataset -> {CLEANED_SOLD_PATH}")


if __name__ == "__main__":
    main()
