"""
Weeks 4-5 - Data cleaning on the Week 1 combined dataset.

"""

import pandas as pd
from pathlib import Path


BASE_DIR = Path(r"C:\IDX-Exchange\csv")

# Regenerated by rerunning week1_aggregation.py with the updated MONTHS list
COMBINED_LISTING_PATH = BASE_DIR / "CRMLSListing_Combined_Residential.csv"
COMBINED_SOLD_PATH = BASE_DIR / "CRMLSSold_Combined_Residential.csv"

# Output
CLEANED_LISTING_PATH = BASE_DIR / "week4_cleaned_listing.csv"
CLEANED_SOLD_PATH = BASE_DIR / "week4_cleaned_sold.csv"

DATE_COLS = [
    "CloseDate",
    "PurchaseContractDate",
    "ListingContractDate",
    "ContractStatusChangeDate",
]
NUMERIC_COLS = [
    "ClosePrice",
    "LivingArea",
    "DaysOnMarket",
    "BedroomsTotal",
    "BathroomsTotalInteger",
]

# California bounding box for plausibility checks
CA_LAT_RANGE = (32.0, 42.0)
CA_LNG_RANGE = (-125.0, -114.0)


DROP_COLUMNS = [
    "BusinessType", "CoveredSpaces", "MiddleOrJuniorSchoolDistrict", "TaxYear",
    "FireplacesTotal", "TaxAnnualAmount", "AboveGradeFinishedArea", "ElementarySchoolDistrict",
    "CoBuyerAgentFirstName", "BuyerAgencyCompensation", "BuyerAgencyCompensationType", "BuilderName",
    "LotSizeDimensions", "BuildingAreaTotal",
]

FILL_COLUMNS = {
    "WaterfrontYN": "N",
    "BasementYN": "N",
    "BelowGradeFinishedArea": 0,
}



def drop_redundant_columns(df: pd.DataFrame) -> pd.DataFrame:
    dup_cols = [c for c in df.columns if c.endswith(".1")]
    for dup in dup_cols:
        original = dup[:-2]
        if original in df.columns:
            both_filled = df[original].notna() & df[dup].notna()
            mismatches = (df.loc[both_filled, original].astype(str)
                          != df.loc[both_filled, dup].astype(str)).sum()
            if mismatches:
                print(f"  WARNING: '{original}' vs '{dup}' differ in {mismatches:,} rows - kept '{original}', dropped '{dup}'")
    if dup_cols:
        print(f"  Dropped {len(dup_cols)} redundant duplicate-named columns: {dup_cols}")
        df = df.drop(columns=dup_cols)
    return df



def drop_unnecessary_columns(df: pd.DataFrame) -> pd.DataFrame:
    present = [c for c in DROP_COLUMNS if c in df.columns]
    if present:
        df = df.drop(columns=present)
        print(f"  Dropped {len(present)} unnecessary columns: {present}")
    return df


def handle_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    for col, fill_value in FILL_COLUMNS.items():
        if col in df.columns:
            n_filled = df[col].isna().sum()
            df[col] = df[col].fillna(fill_value)
            if n_filled:
                print(f"  Filled '{col}': {n_filled:,} missing -> '{fill_value}'")
    return df


def clean_dataset(df: pd.DataFrame, label: str) -> pd.DataFrame:
    print(f"\n--- Cleaning {label} ---")
    before_rows = len(df)

    # 0. Remove redundant columns 
    df = drop_redundant_columns(df)

    # 0.5 Remove unnecessary columns 
    df = drop_unnecessary_columns(df)

    # 0.6 Handle missing values 
    df = handle_missing_values(df)

    # 1. Datetime conversion
    for col in DATE_COLS:
        if col in df.columns:
            failed_before = df[col].notna().sum()
            df[col] = pd.to_datetime(df[col], errors="coerce")
            failed_after = df[col].isna().sum() - (before_rows - failed_before)
            print(f"  {col}: converted to datetime "
                  f"({max(failed_after, 0):,} values could not be parsed)")

    # 2. Numeric type enforcement
    for col in NUMERIC_COLS:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # 3. Invalid numeric value flags
    df["invalid_price_flag"] = df.get("ClosePrice", pd.Series(dtype=float)) <= 0
    df["invalid_area_flag"] = df.get("LivingArea", pd.Series(dtype=float)) <= 0
    df["invalid_dom_flag"] = df.get("DaysOnMarket", pd.Series(dtype=float)) < 0
    df["invalid_beds_baths_flag"] = (
        (df.get("BedroomsTotal", pd.Series(dtype=float)) < 0)
        | (df.get("BathroomsTotalInteger", pd.Series(dtype=float)) < 0)
    )

    # 4. Date consistency flags
    df["listing_after_close_flag"] = df["ListingContractDate"] > df["CloseDate"]
    df["purchase_after_close_flag"] = df["PurchaseContractDate"] > df["CloseDate"]
    df["negative_timeline_flag"] = df["ListingContractDate"] > df["PurchaseContractDate"]

    # 5. Geographic checks
    df["missing_coord_flag"] = df["Latitude"].isna() | df["Longitude"].isna()
    df["zero_coord_flag"] = (df["Latitude"] == 0) | (df["Longitude"] == 0)
    df["positive_lng_flag"] = df["Longitude"] > 0
    df["out_of_ca_bounds_flag"] = ~df["Latitude"].between(*CA_LAT_RANGE) | ~df["Longitude"].between(*CA_LNG_RANGE)

    # Summary
    flag_cols = [c for c in df.columns if c.endswith("_flag")]
    print(f"  Rows: {before_rows:,} (row count unchanged - invalid records are flagged, not dropped)")
    print(f"  Columns: {len(df.columns)}")
    for col in flag_cols:
        print(f"  {col}: {int(df[col].sum()):,} flagged")

    return df


def main():
    listing = pd.read_csv(COMBINED_LISTING_PATH, low_memory=False)
    sold = pd.read_csv(COMBINED_SOLD_PATH, low_memory=False)
    print(f"Loaded combined Listing: {len(listing):,} rows")
    print(f"Loaded combined Sold: {len(sold):,} rows")

    listing_clean = clean_dataset(listing, "Listing")
    sold_clean = clean_dataset(sold, "Sold")

    listing_clean.to_csv(CLEANED_LISTING_PATH, index=False)
    sold_clean.to_csv(CLEANED_SOLD_PATH, index=False)

    print(f"\nSaved cleaned Listing dataset -> {CLEANED_LISTING_PATH}")
    print(f"Saved cleaned Sold dataset -> {CLEANED_SOLD_PATH}")


if __name__ == "__main__":
    main()
